# Generated by Django 4.1.1 on 2022-10-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowQ', '0008_alter_patients_wait_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='patient_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='wait_time',
        ),
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='dat',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='mellicod',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
