# Generated by Django 4.1.1 on 2022-11-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowQ', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
