# Generated by Django 4.2.16 on 2024-12-15 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShowQ', '0012_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.BooleanField()),
                ('service_time', models.CharField(choices=[('5', '5 دقیقه'), ('10', '10 دقیقه'), ('15', '15 دقیقه'), ('20', '20 دقیقه'), ('25', '25 دقیقه'), ('30', '30 دقیقه'), ('35', '35 دقیقه'), ('40', '40 دقیقه'), ('45', '45 دقیقه')], default='30', max_length=3)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ShowQ.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ShowQ.doctor')),
            ],
        ),
    ]

# Generated by Django 4.2.16 on 2025-01-03 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShowQ', '0012_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.BooleanField()),
                ('service_time', models.CharField(choices=[('5', '5 دقیقه'), ('10', '10 دقیقه'), ('15', '15 دقیقه'), ('20', '20 دقیقه'), ('25', '25 دقیقه'), ('30', '30 دقیقه'), ('35', '35 دقیقه'), ('40', '40 دقیقه'), ('45', '45 دقیقه')], default='30', max_length=3)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ShowQ.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ShowQ.doctor')),
            ],
        ),
    ]
