# Generated by Django 4.2.16 on 2025-01-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowQ', '0013_doctor_schedule_appointmentsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedulegpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='service_time',
            field=models.CharField(choices=[('5', '5 Min'), ('10', '10 Min'), ('15', '15 Min'), ('20', '20 Min'), ('25', '25 Min'), ('30', '30 Min'), ('35', '35 Min'), ('40', '40 Min'), ('45', '45 Min')], default='30', max_length=3),
        ),
    ]
