# Generated by Django 4.2.16 on 2025-01-17 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShowQ', '0018_remove_appointmentsmodel_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointmentsmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='appointment_length',
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='service_time',
            field=models.CharField(choices=[('5', '5 Min'), ('10', '10 Min'), ('15', '15 Min'), ('20', '20 Min'), ('25', '25 Min'), ('30', '30 Min'), ('35', '35 Min'), ('40', '40 Min'), ('45', '45 Min')], default='30', max_length=3),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ShowQ.doctor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ShowQ.doctor'),
        ),
    ]
