# Generated by Django 4.2.16 on 2025-01-17 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShowQ', '0019_remove_appointmentsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='service_time',
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='appointment_length',
            field=models.IntegerField(default=10, help_text='Duration of each appointment in minutes'),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='ShowQ.doctor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ShowQ.doctor'),
        ),
    ]
