# Generated by Django 4.2.16 on 2025-01-17 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShowQ', '0021_alter_appointmentsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='ShowQ.doctor'),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='appointment_length',
            field=models.IntegerField(help_text='Duration of each appointment in minutes'),
        ),
    ]
