# Generated by Django 4.2.16 on 2025-01-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowQ', '0022_alter_appointmentsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedulegpt',
        ),
        migrations.RemoveField(
            model_name='schedulegpt2',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctorgpt2',
        ),
        migrations.DeleteModel(
            name='Schedulegpt2',
        ),
    ]
